---
- name: Transfer a PTF group files from repo server to target system, and apply
# This playbook is used for 1st level solution. It will get the PTF group information in catalog. Then call sync_apply_ptf_group role
# to transfer the PTF group files to the target system. Then apply.

# Command example: ansible-playbook ./sync_apply_ptf_group_lv1.yml -e "{'target_system': 'systemA', 'repo_server': 'reposerver', 'ptf_group':
# {'group':'SF99876', 'level': 19}, 'image_root': '/home/test/PTF', 'delete': true, 'ptf_omit_list': [{'5770SS1': 'SI78582'}, {'5770ss1': 'SI78544'}]}"
# The 'delete' parameter specifies whether or not to delete the file install dir on target server after apply. The default value is true.
# The input group level can be omitted in 'ptf_group' parameter.
# The 'image_root' parameter specifies the image files' dir on the repo_server.
# The 'ptf_omit_list' parameter specifies the PTFs which need to be omitted, including product ID and PTF number.
  hosts: '{{ target_system }}'
  gather_facts: false
  collections:
    - ibm.power_ibmi

  vars:
    repo_server: "{{ repo_server }}"

  tasks:
    - name: Refresh PTF DB information in catalog
      ibmi_fix_repo_lv1:
        image_root: "{{ image_root }}"
        action: "refresh"
      delegate_to: "{{ repo_server }}"
      register: fix_repo_refresh_result

    - name: Print the PTF group refresh result
      debug:
        var: fix_repo_refresh_result

    - name: Get the PTF group information in catalog
      ibmi_fix_repo_lv1:
        image_root: "{{ image_root }}"
        checksum: true
        action: "find"
        fields:
          - 'image_path'
          - 'image_files'
          - 'download_date'
          - 'ordered_ptf'
        additional_sql: 'ORDER BY download_date DESC, ordered_ptf_count'
        parameters: "{{ ptf_group }}"
      delegate_to: "{{ repo_server }}"
      register: fix_repo_find_result

    - name: Print the PTF group information
      debug:
        var: fix_repo_find_result

    - block:
        - name: PTF group information is not in catalog
          fail:
            msg: "PTF group information is not in catalog, quit."
      when: fix_repo_find_result.success_list[0].query_result is not defined or fix_repo_find_result.success_list[0].query_result == []

    - name: Compose files name list
      set_fact:
        files_name_list: "{{ files_name_list | default( [] ) + [image_files_var.file] }}"
      loop: "{{ fix_repo_find_result.success_list[0].query_result[0].image_files }}"
      loop_control:
        loop_var: image_files_var

    - name: Print files_name_list
      debug:
        var: files_name_list

    - name: Compose apply list
      set_fact:
        ptf_group_information: "{{ {'file_path': fix_repo_find_result.success_list[0].query_result[0].image_path, 'file_name': files_name_list} }}"

    - name: Print ptf_group_information
      debug:
        var: ptf_group_information

    - name: Include sync_apply_ptf_group role to transfer PTF group files to target ibm i, and apply
      include_role:
        name: sync_apply_ptf_group
      vars:
        ptf_group_info: "{{ ptf_group_information }}"
        src_host: "{{ repo_server }}"
