- hosts: localhost
  collections:
    - ibm.power_ibmi
  tasks:
    - name: run PGM built with STMFs
      ibm.power_ibmi.ibmi_cl_command:
        cmd: CALL {{ build_lib }}/SENDMSG
      register: callpgm
      when: build_with_STMFs|bool
      delegate_to: '{{ item }}'
      with_items:
        - "{{ host_names.split() }}"

    - name: run PGM built from PF members
      ibm.power_ibmi.ibmi_cl_command:
        cmd: CALL {{ build_lib }}/SAMPLECL
      register: callpgm
      when: not build_with_STMFs|bool
      delegate_to: '{{ item }}'
      with_items:
        - "{{ host_names.split() }}"
