# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
# Description:
  # The Analyze Default Passwords (ANZDFTPWD) command allows you to print a report of
  # all the user profiles on the system that have a default password and to take an action
  # against the profiles. A profile has a default password when the profile's password
  # matches the user profile name.

# Restriction: 
  # You must have *ALLOBJ and *SECADM special authorities to use this command.

# Parameters:
  # setDisabled --  Set the collected user profiles to 'disabled' status
  # setExpired --  Set the collected user profiles to 'expired' status

# Example:
  # ansible-playbook ibmi-check-default-passwords.yml
  # ansible-playbook ibmi-check-default-passwords.yml --extra-vars "setExpired=true"
  # ansible-playbook ibmi-check-default-passwords.yml --extra-vars "setDisabled=true setExpired=true"

- hosts: ibmi
  gather_facts: false
  collections:
   - ibm.power_ibmi

  tasks:
  - name: run the CL command ANZDFTPWD to collect all the user profiles that have a default password
    ibmi_cl_command:
      cmd: ANZDFTPWD ACTION(*NONE)
      joblog: true

  - name: query the collected list of user profiles
    ibmi_sql_query:
      sql: "SELECT * FROM QUSRSYS.QASECPWD"
    register: default_password_user_list

  - name: display the collected list of user profiles
    debug:
      msg: "{{ default_password_user_list.row }}"

  - name: set the collected user profiles expired
    ibmi_cl_command:
      cmd: ANZDFTPWD ACTION(*PWDEXP)
      joblog: true
    when: setExpired is defined and setExpired | bool

  - name: set the collected user profiles disabled
    ibmi_cl_command:
      cmd: ANZDFTPWD ACTION(*DISABLE)
      joblog: true
    when: setDisabled is defined and setDisabled | bool

  - name: run the CL command to delete the report file
    ibmi_cl_command:
      cmd: CLRPFM FILE(QUSRSYS/QASECPWD) MBR(*ALL)
      joblog: false
